# Generated by Django 3.0.3 on 2020-03-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pik', '0002_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Vozila', 'Vozila'), ('Namještaj', 'Namještaj'), ('Bela tehnika', 'Bela tehnika'), ('Odjeća', 'Odjeća'), ('Tehnologija', 'Tehnologija'), ('Igračke', 'Igračke'), ('Literatura', 'Literatura'), ('Nekretnine', 'Nekretnine'), ('Ostalo', 'Ostalo')], max_length=12),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(),
        ),
    ]
