# Generated by Django 3.0.3 on 2020-03-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pik', '0005_auto_20200322_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.CharField(choices=[('Iznos', 'Iznos'), ('Po dogovoru', 'Po dogovoru')], max_length=11),
        ),
    ]
